config/routes.rb
Rails.application.routes.draw do
  resources :buildings
  resources :ideas
  resources :items
  devise_for :users

  resources :apps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/index' => 'main#index'

#  root to: redirect('/apps')
end

app/models/building.rb
class Building < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :description, :picture)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building, local: true) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<% @buildings.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |building| %>
      <div class="col-md-4">
        <%= image_tag building.picture_url, width: '100%' if building.picture.present? %>
        <h4><%= link_to building.name, building %></h4>
        <%= building.description %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@building.picture_url, width: '100%') if @building.picture.present? %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @building.name %></p>
    <p><b>Description: </b><%= @building.description %></p>
    <p>
      <%= link_to 'Edit', edit_building_path(@building) %> |
      <%= link_to 'Destroy', @building, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <%= link_to 'Back', building_path %>
    </p>
  </div>
</div>