config/routes.rb
Rails.application.routes.draw do
  resources :buildings
  resources :ideas
  resources :items
  devise_for :users

  resources :apps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/index' => 'main#index'

#  root to: redirect('/apps')
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= app.name %></td>
        <td><%= app.number %></td>
        <td><%= app.comment %></td>
        <td><%= link_to 'Show', app %></td>
        <td><%= link_to 'Edit', edit_app_path(app) %></td>
        <td><%= link_to 'Destroy', app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @app.number %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @app.comment %>
</p>

<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>